<?php
// Generated by gen_types.py's data — weekly tips per Kibbe type (rotated by ISO week).
return [
  "dramatic" => [
  "name" => "Dramatic",
  "tips" => ["Long, unbroken vertical lines: a column dress, a floor-length coat, a single-breasted suit worn as one piece.", "Crisp, structured fabrics with some weight — gabardine, heavy crepe, leather, dense wool — that hold a sharp edge.", "One large, bold detail rather than many small ones: an oversized lapel, a single statement earring, a wide belt.", "Sharp geometry in accessories: pointed toes, angular bags, long straight pendants.", "Skip this one: Small, fussy details — ruffles, tiny prints, delicate jewelry — get lost on a long, sharp frame.", "Skip this one: Soft, clingy or overly draped fabrics blur the lines that are your strongest feature."],
  "outfits" => ["A black column dress, sharp pointed pumps, one long metal earring.", "A long camel overcoat over a slim turtleneck and straight trousers, all in one tone.", "A leather jacket with a strong shoulder, high-waisted wide trousers, a structured tote."]
],
  "soft-dramatic" => [
  "name" => "Soft Dramatic",
  "tips" => ["Long lines built in liquid fabrics: bias-cut silk, matte jersey, velvet, satin that pools and drapes.", "Draped detail that follows the body — a cowl neck, a wrap dress, a sarong skirt, a plunging neckline.", "Glamour at scale: large jewelry, a dramatic sleeve, a bold print that is big rather than busy.", "Waist emphasis with softness — a sash or a soft belt rather than a rigid one.", "Skip this one: Stiff, boxy tailoring with no waist reads heavy on a curvy, elongated frame.", "Skip this one: Tiny, dainty details disappear; a delicate chain does nothing for you."],
  "outfits" => ["A bias-cut emerald slip dress, gold cuff, strappy heels.", "A draped wrap top tucked into wide fluid trousers, with one oversized hoop.", "A long soft-shouldered coat over a knit column dress, belted loosely."]
],
  "flamboyant-natural" => [
  "name" => "Flamboyant Natural",
  "tips" => ["Relaxed, unconstructed tailoring: an oversized blazer, a long trench, a boyfriend coat.", "Natural textures with body — linen, suede, chunky knit, raw denim, tweed.", "Long, easy layers that drape rather than cinch; asymmetry and undone details.", "Chunky, organic accessories: a wide leather cuff, a big slouchy bag, a flat wide-brim hat.", "Skip this one: Anything fitted through the shoulder and rigid — a sharp, tight jacket looks borrowed.", "Skip this one: Symmetry and precision: matching sets, tiny neat details, delicate jewelry."],
  "outfits" => ["An oversized camel blazer, white tee, straight jeans and loafers.", "A long knit cardigan over a slip skirt with flat boots.", "A linen jumpsuit with rolled sleeves and a wide leather belt sitting low."]
],
  "natural" => [
  "name" => "Natural",
  "tips" => ["Clean, easy shapes with a relaxed fit: a straight coat, a boxy jacket, a simple shift.", "Matte, textured fabrics — cotton, wool, linen, suede — in earthy or muted tones.", "Minimal ornamentation; let the texture and the cut do the talking.", "Practical, mid-scale accessories: a leather satchel, a plain belt, a wooden bangle.", "Skip this one: Stiff, sharp tailoring with exaggerated shoulders.", "Skip this one: Ornate detail — ruffles, sequins, lace — reads fussy against blunt, broad lines."],
  "outfits" => ["A boxy denim jacket, a plain tee, wide cropped trousers and white sneakers.", "A relaxed wool coat over a rib knit dress with ankle boots.", "A linen shirt half-tucked into tapered chinos, leather sandals."]
],
  "soft-natural" => [
  "name" => "Soft Natural",
  "tips" => ["Relaxed shapes with a gently defined waist: a wrap dress in a soft fabric, a belted cardigan.", "Soft, slightly textured fabrics — brushed cotton, jersey, fine knit, washed silk.", "Rounded, unfussy details: a scoop neck, a soft blouse, a slightly gathered skirt.", "Natural, mid-scale accessories with a little softness — a rounded bag, a hoop earring.", "Skip this one: Rigid tailoring and sharp shoulders overwhelm the softness.", "Skip this one: Heavy embellishment and very ornate prints."],
  "outfits" => ["A soft wrap dress in rust jersey with tan flat sandals.", "An oversized cardigan belted over a slip skirt, ankle boots.", "A washed-silk blouse tucked into straight jeans with a rounded shoulder bag."]
],
  "dramatic-classic" => [
  "name" => "Dramatic Classic",
  "tips" => ["Precise tailoring with a slight edge: a sharp-lapel blazer, a pencil skirt, a tailored shirt dress.", "Smooth, medium-weight fabrics with structure — crepe, fine wool, cotton sateen.", "Symmetrical, clean lines and a little contrast: a crisp collar, a defined shoulder.", "Polished, geometric accessories: a structured bag, a pointed flat, a simple chain.", "Skip this one: Slouchy, unstructured pieces look untidy rather than relaxed.", "Skip this one: Heavy ornamentation and romantic detail."],
  "outfits" => ["A navy sharp-shouldered blazer, white shirt, cigarette trousers and pointed flats.", "A tailored shirt dress with a slim belt and a structured bag.", "A fine-knit top with a pencil skirt and block-heel pumps."]
],
  "classic" => [
  "name" => "Classic",
  "tips" => ["Balanced, symmetrical, moderate everything: a well-cut blazer, a knee-length skirt, a simple sheath.", "Smooth, refined fabrics — fine wool, silk blends, quality cotton — in clean solids or subtle patterns.", "Timeless details: a notched collar, a straight hem, a neat cuff.", "Understated, medium-scale accessories: pearl studs, a leather loafer, a classic tote.", "Skip this one: Anything extreme — oversized, ultra-fitted, very ornate or very undone.", "Skip this one: Loud prints and heavy texture that disrupt the smoothness."],
  "outfits" => ["A camel sheath dress, nude pumps and a slim watch.", "A grey blazer, silk shell, straight trousers and loafers.", "A trench over a fine-knit top and a straight midi skirt."]
],
  "soft-classic" => [
  "name" => "Soft Classic",
  "tips" => ["Balanced shapes softened at the edges: a rounded lapel, a slightly gathered sleeve, a soft sheath.", "Smooth fabrics with a little drape — crepe de chine, soft wool, matte jersey.", "Gentle waist definition and rounded necklines.", "Refined, slightly delicate accessories: a small pendant, a rounded-toe pump, a soft leather bag.", "Skip this one: Sharp, angular tailoring and hard geometric details.", "Skip this one: Anything heavy, chunky or oversized."],
  "outfits" => ["A blush wrap blouse, straight cream trousers and rounded-toe flats.", "A soft sheath dress with a slim belt and a small structured bag.", "A fine cardigan over a scoop-neck top with a flowing midi skirt."]
],
  "flamboyant-gamine" => [
  "name" => "Flamboyant Gamine",
  "tips" => ["Sharp, compact tailoring: a cropped jacket, a boxy blazer, a straight mini skirt.", "Crisp fabrics with graphic contrast — bold stripes, colorblocking, geometric prints.", "Broken-up lines and mixed pieces rather than one long silhouette.", "Playful, angular accessories: a chunky sneaker, a geometric earring, a small structured bag.", "Skip this one: Long, unbroken flowing lines that swallow a compact frame.", "Skip this one: Soft, draped, romantic detail."],
  "outfits" => ["A cropped leather jacket, striped tee, straight jeans and loafers.", "A boxy tweed jacket with a mini skirt and ankle boots.", "A colorblocked knit with tapered trousers and a chunky sneaker."]
],
  "gamine" => [
  "name" => "Gamine",
  "tips" => ["Compact, mixed shapes: a fitted top with a straight skirt, a short jacket over a slim dress.", "Crisp fabrics and lively details — contrast trim, buttons, small graphic prints.", "Broken lines and a bit of contrast in every outfit; a mix of sharp and soft.", "Small-to-medium, playful accessories: a beret, a small crossbody, a stud earring.", "Skip this one: Long, heavy, flowing pieces that overwhelm a small frame.", "Skip this one: Very plain, monochrome, unbroken looks that read flat on you."],
  "outfits" => ["A fitted striped top, a cropped cardigan and a straight mini skirt.", "A short trench over a slim knit dress with flat ankle boots.", "A collared blouse with contrast buttons, tapered trousers and loafers."]
],
  "soft-gamine" => [
  "name" => "Soft Gamine",
  "tips" => ["Compact shapes with a little curve: a fitted cardigan, a rounded-collar blouse, a flared mini skirt.", "Soft, slightly textured fabrics — fine knit, cotton with stretch, lightweight tweed.", "Playful, rounded detail: a peter pan collar, a puff sleeve, a bow at small scale.", "Small, sweet accessories: a rounded bag, a ballet flat, a small hoop.", "Skip this one: Long, straight, severe lines and hard geometry.", "Skip this one: Oversized, heavy or very structured pieces."],
  "outfits" => ["A fitted rounded-collar blouse, a flared mini skirt and ballet flats.", "A cropped cardigan over a fit-and-flare dress with a small crossbody.", "A soft knit top, high-waisted cropped trousers and a rounded loafer."]
],
  "theatrical-romantic" => [
  "name" => "Theatrical Romantic",
  "tips" => ["Fitted, curve-following shapes with a sharp accent: a corseted top, a wrap dress with a deep V, a pencil skirt.", "Luxurious, fluid fabrics — silk, satin, velvet, fine lace — that hug rather than hang.", "Waist emphasis always, plus one sharp detail: a pointed shoe, a defined shoulder, a bold earring.", "Small-scale, glamorous accessories: delicate but sparkly, never chunky.", "Skip this one: Boxy, loose or heavy pieces that hide the curve.", "Skip this one: Rough, matte, oversized textures."],
  "outfits" => ["A fitted wrap dress in ruby satin with pointed slingbacks.", "A corset-style top, a high-waisted pencil skirt and a small jeweled clutch.", "A fitted knit with a draped midi skirt and a delicate drop earring."]
],
  "romantic" => [
  "name" => "Romantic",
  "tips" => ["Soft, curve-following silhouettes: a draped dress, a rounded neckline, a gathered waist.", "Plush, fluid fabrics — velvet, chiffon, jersey, cashmere, soft lace.", "Rounded detail everywhere: ruffles at small scale, soft bows, a scoop or sweetheart neckline.", "Delicate, rounded, slightly ornate accessories: a pearl drop, a soft satchel, a rounded-toe heel.", "Skip this one: Sharp tailoring, straight boxy lines and hard geometry.", "Skip this one: Rough or stiff textures — heavy denim, canvas, leather with a hard edge."],
  "outfits" => ["A draped blush dress with a sweetheart neckline and rounded-toe heels.", "A soft cashmere sweater tucked into a flowing midi skirt with ballet flats.", "A velvet wrap top, a gathered satin skirt and a pearl drop earring."]
]
];
