<?php
// Read-only token for api/client_errors_summary.php (anonymised bug-report
// counts). Generated by Claude on 2026-09-15; it grants nothing but that
// summary. Rotate by replacing the string and updating the watchdog routine.
const WATCHDOG_READ_TOKEN = '0ed12502b6a9e9a4ea28b339627132c44e35b05c47cbe405';
